apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sample-staging
resources:
  - ../../base
  - ingress.yaml
images:
  - name: sample-backend
    newName: cnoe.localtest.me:8443/giteaadmin/sample-backend-app
    newTag: placeholder
